name: Deploy React to EC2

on:
  push:
    branches:
      - release-front

env:
  S3_BUCKET_NAME: issuetracker-web
  CODE_DEPLOY_APPLICATION_NAME: issue-tracker-react
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: issuetracker-react
  CI: false

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install dependencies    # 의존 파일 설치
        run: npm install
        working-directory: ./fe

      - name: Generate build          # React Build
        run: npm run build
        working-directory: ./fe
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        working-directory: ./fe
        shell: bash

      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://issuetracker-web

      

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 


      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip


      - name: Code Deploy
        run: | 
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
